@startuml
actor Frontend as FE
participant  "LikeController" as Controller
participant  "LikeService" as Service

FE -> Controller: 发起点赞请求
activate Controller

Controller -> Controller: 检查用户登录状态
Controller -> Controller: 记录点赞日志
Controller -> Service: 查询用户是否已点赞
activate Service

Service --> Controller: 返回点赞状态
Controller -> Service: 调用save方法保存点赞记录
Service --> Controller: 返回保存结果
Controller --> FE: 返回点赞结果
deactivate Service
deactivate Controller
@enduml
